Document: helloworld-deb-sample
Title: Debian helloworld-deb-sample Manual
Author: <insert document author here>
Abstract: This manual describes what helloworld-deb-sample is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/helloworld-deb-sample/helloworld-deb-sample.sgml.gz

Format: postscript
Files: /usr/share/doc/helloworld-deb-sample/helloworld-deb-sample.ps.gz

Format: text
Files: /usr/share/doc/helloworld-deb-sample/helloworld-deb-sample.text.gz

Format: HTML
Index: /usr/share/doc/helloworld-deb-sample/html/index.html
Files: /usr/share/doc/helloworld-deb-sample/html/*.html
